name: image_whisperer
version: 0.9.0+1
author: Peter Siroki <psiroki@skawa.hu>
description: Rotate and resize images before uploading as necessary
homepage: https://github.com/skawa-universe/image_whisperer

dependencies:
  exifdart: ">=0.5.0+2 <0.6.0"
